### ISSUE TITLE
Order does not work properly for two columns from a SciDB Dataframe

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDBR#70] opened 2015-07-24 14:37 UTC
Order does not work properly for two columns from a SciDB Dataframe    

    EXAMPLE CODE
    foo = scidb("result")
    scidbremove(foo,force=TRUE)
    iquery(sprintf("create array result <corr:double NULL> [selected=0:*,3,0, compound_id=0:*,4,0]"))
    iquery(sprintf("store(build(result,'[[9.0,1,5,3],[8,14,2,4],[10,1,6,7]]',true),result)"))
    rankquerystr = sprintf("store(rank(result, corr, compound_id),resultranked)")
    iquery(rankquerystr)
    filterstep=scidb("resultranked")
    print(filterstep[])
   
    #filternum - Number that you would like to return i.e. 250
    filternum=2 
    evalstr=sprintf("corr_rank<%d", filternum)
    filterout = subset(filterstep, evalstr, eval='true')[]
    print(filterout)
    
  The below breaks because of a namespace problem. It works if you include the correct namespace. 
   newdata <- filterout[base::order(compound_id, corr),]
    print(newdata)

**Comment by bwlewis** [comment] 2015-07-27 21:14
Duplicate of #42.

**Closed by bwlewis** 2015-07-27 21:14 UTC
Labels: bug, duplicate
