### ISSUE TITLE
curl_fetch_memory performance issues

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDBR#198] opened 2019-06-16 20:34 UTC
Inspired by some recent work, here's a case where it looks like we can do much better. This was run on a 48-instance SciDB. Pretty much all of the download time is spent in R.

Setup:
```R
iquery(db, "
 store(
  apply(
   build(<a:int64> [x=1:30000000,10000,0], random()%20), 
   b, int64(random()%250000000), 
   c, 'c'+string(random()%200), 
   d, 'd'+string(random()%200), 
   e, 'e'+string(random()%1000000)
  ),
  temp
 )")
```

The test is to simply time a download via SciDBR. For this array the download time is highly variable - jumping from 100 to 300 seconds. This was timed on a ubuntu system and I'll look into CentOS next:
```R
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 33.319 299.232 334.406 
```

We *know* we can do better because this works as an alternative - with a text format of all things:
```R
> t1=proc.time()
> iquery(db, "aio_save(temp, '/home/scidb/foo.txt', 'format=tsv')")
> y = data.frame(data.table::fread('/home/scidb/foo.txt'))
> print(proc.time()-t1)
   user  system elapsed 
 40.519   0.677  12.182 

> colnames(y) = colnames(x)
> x=x[order(x$a, x$b, x$c, x$d, x$e), ]
> y=y[order(y$a, y$b, y$c, y$d, y$e), ]
> rownames(x) = NULL
> rownames(y) = NULL
> all.equal(x,y)
[1] TRUE
```

**Comment by apoliakov** [comment] 2019-06-16 21:07
I've tried the experiment on CentOS 7 with a newer version of R (3.5.1). At first, we ran faster. But after a few iterations we got back to the timings we saw earlier - as if running out of some resource.

```R
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 23.516   8.653  34.629 


> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 25.506  67.795  95.883 


> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 26.490 268.336 297.471 


> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 25.160   9.733  37.525 


> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 25.999 159.459 188.094
```

When these "skidmarks" are happening, `perf top` shows most time spent in `move_page_tables`:
```
Samples: 1M of event 'cycles', Event count (approx.): 64046582714
Overhead  Shared Object                          Symbol                                                                  ◆
  41.92%  [kernel]                               [k] move_page_tables                                                    ▒
   4.53%  [kernel]                               [k] native_set_pte_at                                                   ▒
   3.10%  [kernel]                               [k] unmap_page_range                                                    ▒
   2.79%  libc-2.17.so                           [.] __memmove_ssse3_back                                                ▒
   2.42%  [kernel]                               [k] _raw_qspin_lock                                                     ▒
   2.02%  [kernel]                               [k] copy_user_enhanced_fast_string                                      ▒
```

**Comment by apoliakov** [comment] 2019-06-16 22:51
The debug output is illustrative. It suggests that most of the variability happens in the `curl_fetch_memory` function:

```R
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
show('filter(scan(temp), true)', 'afl')

Query time 0.188
Data transfer time 0.01 
R parsing time 0 
Data query scan(temp)
Format (int64 null,int64 ,string ,string ,string )
scan(temp)

Query time 1.451
Data transfer time 198.378999999999         #<<--- this is the part that varies
  R buffer 4378830/1313674166 bytes parsing time 0.07
  R rbind/df assembly time 0.002
  R buffer 1313674166/1313674166 bytes parsing time 20.23
  R rbind/df assembly time 9.235
Total R parsing time 29.54
> print(proc.time()-t1)
   user  system elapsed 
 40.459 197.178 239.289 
```

**Comment by apoliakov** [comment] 2019-06-18 00:42
Some notes:
0) no quick solutions are obvious
1) may want to try curl download to file
2) may want to try setting a "curl option" for a buffer size
3) may want to try, on the shim side, to increase the "chunk size" of HTTP transfer

**Comment by apoliakov** [comment] 2019-06-18 21:29
Machine restart seems to make it go away, and then it comes back. So the behavior is definitely one of "ramp-up":

```R
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 23.741   3.743  28.910 
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 24.177  10.513  36.091 
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 24.505   6.817  32.710 
> t1=proc.time() 
> x = iquery(db, "scan(temp)", return=T, only_attributes=T)
> print(proc.time()-t1)
   user  system elapsed 
 27.723 162.761 191.908 
```

**Comment by apoliakov** [comment] 2019-06-19 22:01
Narrowing the scope of this to just `curl_fetch_memory` issues. The parsing could also use a look but we'll look at that in a different issue.

**Comment by ksens** [comment] 2019-07-25 13:08
For reference, archiving the performance reports using this fix for the `revealgenomics` API

### MMRF-14: Cufflinks Transcript -- much more stable download times
```
# Before curl fix
idx: 1 -- time (sec): 82.38
idx: 2 -- time (sec):103.17
idx: 3 -- time (sec): 81.35
idx: 4 -- time (sec): 79.64
idx: 5 -- time (sec): 82.91

# After curl fix
idx: 1 -- time (sec): 81.08
idx: 2 -- time (sec): 81.28
idx: 3 -- time (sec): 81.91
idx: 4 -- time (sec): 81.75
idx: 5 -- time (sec): 81.92
```

### MMRF-14: Cufflinks Gene -- not much of a change

The download is much smaller this time
```
# Before curl fix
idx: 1 -- time (sec): 30.88
idx: 2 -- time (sec): 31.41
idx: 3 -- time (sec): 24.93
idx: 4 -- time (sec): 24.92
idx: 5 -- time (sec): 31.19

# After curl fix
idx: 1 -- time (sec): 25.24
idx: 2 -- time (sec): 30.73
idx: 3 -- time (sec): 24.47
idx: 4 -- time (sec): 30.02
idx: 5 -- time (sec): 30.48
```

**Comment by ksens** [comment] 2019-10-14 11:50
FYI -- issue filed by @apoliakov on original `curl` repo seems to have been closed (https://github.com/jeroen/curl/issues/189), and the update is now available at CRAN. 

We should not have to do the following anymore:
```sh
sudo R --slave -e "devtools::install_github('paradigm4/curl', ref='realloc_fix')"
```

and should be able to install from CRAN directly. 

## Verification

This is what I got for timing for original `temp` array used in the ticket

```R
iquery(db, "
  store(
   apply(
    build(<a:int64> [x=1:30000000,10000,0], random()%20), 
    b, int64(random()%250000000), 
    c, 'c'+string(random()%200), 
    d, 'd'+string(random()%200), 
    e, 'e'+string(random()%1000000)
   ),
   temp
  )")
options(scidb.result_size_limit = 4*1024)
system.time({x = iquery(db, "scan(temp)", return=T, only_attributes=T)})[3]
# elapsed 
# 58.179 
system.time({x = iquery(db, "scan(temp)", return=T, only_attributes=T)})[3]
# elapsed 
# 58.718 
system.time({x = iquery(db, "scan(temp)", return=T, only_attributes=T)})[3]
# elapsed 
# 56.088 
```

Would request someone to verify and then we can close this ticket.

**Comment by ksens** [comment] 2020-11-05 06:05
Closing issue as the root cause was resolved in the `curl` package via https://github.com/jeroen/curl/issues/189

**Closed by ksens** 2020-11-05 06:05 UTC
